version: 0.2

phases:

  pre_build:
    commands:
    - echo logging into ecr
    - mvn clean package
    - aws --version
    
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPO
  
    - REPOSITORY_URI=$REPO/springapp
   
    - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
   
    
    
  build:
    commands:
    - echo building the docker images
    - docker build -t $REPOSITORY_URI:latest .
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  
  post_build:
    commands:
    - echo pushing the docker image
    - echo $REPOSITORY_URI:$IMAGE_TAG   
    - docker push $REPOSITORY_URI:latest
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    
    - printf '[{"name":"springappcontainer","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    - cat imagedefinitions.json     

artifacts:
  files: imagedefinitions.json     